export const SERVICES = [
    {
        id: '01',
        title: 'Web App Development',
        description: 'High-performance web applications built with React 19, Next.js 15, and TypeScript. From SaaS platforms to complex dashboards.',
        features: ['React / Next.js', 'TypeScript', 'REST & GraphQL APIs', 'Real-time with Websockets'],
        icon: '🌐',
        accent: '#0284c7',
        size: 'large',
    },
    {
        id: '02',
        title: 'Mobile Apps',
        description: 'Native-feel iOS and Android applications. Cross-platform with React Native.',
        features: ['React Native', 'iOS & Android', 'Push Notifications', 'Offline-first'],
        icon: '📱',
        accent: '#6366f1',
        size: 'small',
    },
    {
        id: '03',
        title: 'UI/UX Design',
        description: 'Awwwards-quality interfaces. From wireframes to pixel-perfect handoff.',
        features: ['Figma Design Systems', 'Prototyping', 'User Research', 'Accessibility (WCAG)'],
        icon: '✦',
        accent: '#2563eb',
        size: 'small',
    },
    {
        id: '04',
        title: 'Cloud & DevOps',
        description: 'Scalable cloud infrastructure. CI/CD pipelines. Zero-downtime deployments.',
        features: ['AWS / GCP', 'Docker & Kubernetes', 'CI/CD Pipelines', 'Monitoring & Alerts'],
        icon: '☁',
        accent: '#10b981',
        size: 'small',
    },
    {
        id: '05',
        title: 'Custom Software',
        description: 'End-to-end custom software tailored exactly to your business logic and scale requirements.',
        features: ['System Architecture', 'API Development', 'Database Design', 'Maintenance & Support'],
        icon: '⚙',
        accent: '#f59e0b',
        size: 'small',
    },
];
