export const STEPS = [
    {
        step: '01',
        title: 'Discover',
        subtitle: 'Research & strategy',
        description: 'We deep-dive into your business goals, target users, and technical landscape. Every constraint is mapped and every opportunity identified before a single line of code is written.',
        tags: ['User research', 'Competitive analysis', 'Technical scoping', 'Roadmap planning'],
        accent: '#0d9488',
        icon: '◎',
        metric: { value: '100%', label: 'Alignment before kickoff' },
    },
    {
        step: '02',
        title: 'Design',
        subtitle: 'UI/UX & prototyping',
        description: 'Interfaces built on a bulletproof design system. Wireframes to high-fidelity prototypes, validated with real user feedback before development begins.',
        tags: ['Design systems', 'Interactive prototypes', 'Accessibility (WCAG)', 'Brand alignment'],
        accent: '#7c3aed',
        icon: '◆',
        metric: { value: '3×', label: 'Faster dev with design tokens' },
    },
    {
        step: '03',
        title: 'Develop',
        subtitle: 'Agile engineering',
        description: 'Production-grade code in two-week sprints. Every pull request is reviewed, tested, and benchmarked. CI/CD pipelines keep the main branch always deployable.',
        tags: ['Next.js / React', 'TypeScript', 'CI/CD pipelines', 'Performance audits'],
        accent: '#2563eb',
        icon: '◉',
        metric: { value: '99%', label: 'Test coverage target' },
    },
    {
        step: '04',
        title: 'Deploy',
        subtitle: 'Launch & scale',
        description: 'Zero-downtime production releases on cloud infrastructure with real-time monitoring. We stay with you after launch, iterating and scaling as your business grows.',
        tags: ['Cloud infra (AWS/GCP)', 'Zero-downtime deploy', 'Monitoring & alerts', 'Post-launch support'],
        accent: '#d97706',
        icon: '◈',
        metric: { value: '24/7', label: 'Monitoring & on-call support' },
    },
];
