import { CountryOption } from "@/types/country";

export const COUNTRIES: CountryOption[] = [
    { flag: "🇦🇫", iso: "af", name: "Afghanistan", code: "+93", phoneLength: 9 },
    { flag: "🇦🇱", iso: "al", name: "Albania", code: "+355", phoneLength: 9 },
    { flag: "🇩🇿", iso: "dz", name: "Algeria", code: "+213", phoneLength: 9 },
    { flag: "🇦🇸", iso: "as", name: "American Samoa", code: "+1", phoneLength: 10 },
    { flag: "🇦🇩", iso: "ad", name: "Andorra", code: "+376", phoneLength: 6 },
    { flag: "🇦🇴", iso: "ao", name: "Angola", code: "+244", phoneLength: 9 },
    { flag: "🇦🇮", iso: "ai", name: "Anguilla", code: "+1", phoneLength: 10 },
    { flag: "🇦🇬", iso: "ag", name: "Antigua and Barbuda", code: "+1", phoneLength: 10 },
    { flag: "🇦🇷", iso: "ar", name: "Argentina", code: "+54", phoneLength: 10 },
    { flag: "🇦🇲", iso: "am", name: "Armenia", code: "+374", phoneLength: 6 },
    { flag: "🇦🇼", iso: "aw", name: "Aruba", code: "+297", phoneLength: 7 },
    { flag: "🇦🇺", iso: "au", name: "Australia", code: "+61", phoneLength: 9 },
    { flag: "🇦🇹", iso: "at", name: "Austria", code: "+43", phoneLength: 10 },
    { flag: "🇦🇿", iso: "az", name: "Azerbaijan", code: "+994", phoneLength: 9 },
    { flag: "🇧🇸", iso: "bs", name: "Bahamas", code: "+1", phoneLength: 10 },
    { flag: "🇧🇭", iso: "bh", name: "Bahrain", code: "+973", phoneLength: 8 },
    { flag: "🇧🇩", iso: "bd", name: "Bangladesh", code: "+880", phoneLength: 10 },
    { flag: "🇧🇧", iso: "bb", name: "Barbados", code: "+1", phoneLength: 10 },
    { flag: "🇧🇾", iso: "by", name: "Belarus", code: "+375", phoneLength: 9 },
    { flag: "🇧🇪", iso: "be", name: "Belgium", code: "+32", phoneLength: 9 },
    { flag: "🇧🇿", iso: "bz", name: "Belize", code: "+501", phoneLength: 7 },
    { flag: "🇧🇯", iso: "bj", name: "Benin", code: "+229", phoneLength: 8 },
    { flag: "🇧🇲", iso: "bm", name: "Bermuda", code: "+1", phoneLength: 10 },
    { flag: "🇧🇹", iso: "bt", name: "Bhutan", code: "+975", phoneLength: 7 },
    { flag: "🇧🇴", iso: "bo", name: "Bolivia", code: "+591", phoneLength: 9 },
    { flag: "🇧🇦", iso: "ba", name: "Bosnia and Herzegovina", code: "+387", phoneLength: 8 },
    { flag: "🇧🇼", iso: "bw", name: "Botswana", code: "+267", phoneLength: 7 },
    { flag: "🇧🇷", iso: "br", name: "Brazil", code: "+55", phoneLength: 11 },
    { flag: "🇻🇬", iso: "vg", name: "British Virgin Islands", code: "+1", phoneLength: 10 },
    { flag: "🇧🇳", iso: "bn", name: "Brunei", code: "+673", phoneLength: 7 },
    { flag: "🇧🇬", iso: "bg", name: "Bulgaria", code: "+359", phoneLength: 9 },
    { flag: "🇧🇫", iso: "bf", name: "Burkina Faso", code: "+226", phoneLength: 8 },
    { flag: "🇧🇮", iso: "bi", name: "Burundi", code: "+257", phoneLength: 8 },
    { flag: "🇰🇭", iso: "kh", name: "Cambodia", code: "+855", phoneLength: 9 },
    { flag: "🇨🇲", iso: "cm", name: "Cameroon", code: "+237", phoneLength: 9 },
    { flag: "🇨🇦", iso: "ca", name: "Canada", code: "+1", phoneLength: 10 },
    { flag: "🇨🇻", iso: "cv", name: "Cape Verde", code: "+238", phoneLength: 7 },
    { flag: "🇰🇾", iso: "ky", name: "Cayman Islands", code: "+1", phoneLength: 10 },
    { flag: "🇨🇫", iso: "cf", name: "Central African Republic", code: "+236", phoneLength: 8 },
    { flag: "🇹🇩", iso: "td", name: "Chad", code: "+235", phoneLength: 8 },
    { flag: "🇨🇱", iso: "cl", name: "Chile", code: "+56", phoneLength: 9 },
    { flag: "🇨🇳", iso: "cn", name: "China", code: "+86", phoneLength: 11 },
    { flag: "🇨🇴", iso: "co", name: "Colombia", code: "+57", phoneLength: 10 },
    { flag: "🇰🇲", iso: "km", name: "Comoros", code: "+269", phoneLength: 7 },
    { flag: "🇨🇬", iso: "cg", name: "Congo (Republic)", code: "+242", phoneLength: 7 },
    { flag: "🇨🇩", iso: "cd", name: "Congo (Democratic Republic)", code: "+243", phoneLength: 7 },
    { flag: "🇨🇰", iso: "ck", name: "Cook Islands", code: "+682", phoneLength: 5 },
    { flag: "🇨🇷", iso: "cr", name: "Costa Rica", code: "+506", phoneLength: 8 },
    { flag: "🇭🇷", iso: "hr", name: "Croatia", code: "+385", phoneLength: 9 },
    { flag: "🇨🇺", iso: "cu", name: "Cuba", code: "+53", phoneLength: 8 },
    { flag: "🇨🇼", iso: "cw", name: "Curaçao", code: "+599", phoneLength: 7 },
    { flag: "🇨🇾", iso: "cy", name: "Cyprus", code: "+357", phoneLength: 8 },
    { flag: "🇨🇿", iso: "cz", name: "Czech Republic", code: "+420", phoneLength: 9 },
    { flag: "🇩🇰", iso: "dk", name: "Denmark", code: "+45", phoneLength: 8 },
    { flag: "🇩🇯", iso: "dj", name: "Djibouti", code: "+253", phoneLength: 6 },
    { flag: "🇩🇲", iso: "dm", name: "Dominica", code: "+1", phoneLength: 10 },
    { flag: "🇩🇴", iso: "do", name: "Dominican Republic", code: "+1", phoneLength: 10 },
    { flag: "🇪🇨", iso: "ec", name: "Ecuador", code: "+593", phoneLength: 9 },
    { flag: "🇪🇬", iso: "eg", name: "Egypt", code: "+20", phoneLength: 10 },
    { flag: "🇸🇻", iso: "sv", name: "El Salvador", code: "+503", phoneLength: 8 },
    { flag: "🇬🇶", iso: "gq", name: "Equatorial Guinea", code: "+240", phoneLength: 9 },
    { flag: "🇪🇷", iso: "er", name: "Eritrea", code: "+291", phoneLength: 7 },
    { flag: "🇪🇪", iso: "ee", name: "Estonia", code: "+372", phoneLength: 8 },
    { flag: "🇸🇿", iso: "sz", name: "Eswatini", code: "+268", phoneLength: 8 },
    { flag: "🇪🇹", iso: "et", name: "Ethiopia", code: "+251", phoneLength: 9 },
    { flag: "🇫🇯", iso: "fj", name: "Fiji", code: "+679", phoneLength: 7 },
    { flag: "🇫🇮", iso: "fi", name: "Finland", code: "+358", phoneLength: 9 },
    { flag: "🇫🇷", iso: "fr", name: "France", code: "+33", phoneLength: 9 },
    { flag: "🇬🇦", iso: "ga", name: "Gabon", code: "+241", phoneLength: 7 },
    { flag: "🇬🇲", iso: "gm", name: "Gambia", code: "+220", phoneLength: 7 },
    { flag: "🇬🇪", iso: "ge", name: "Georgia", code: "+995", phoneLength: 9 },
    { flag: "🇩🇪", iso: "de", name: "Germany", code: "+49", phoneLength: 10 },
    { flag: "🇬🇭", iso: "gh", name: "Ghana", code: "+233", phoneLength: 9 },
    { flag: "🇬🇷", iso: "gr", name: "Greece", code: "+30", phoneLength: 10 },
    { flag: "🇬🇩", iso: "gd", name: "Grenada", code: "+1", phoneLength: 10 },
    { flag: "🇬🇹", iso: "gt", name: "Guatemala", code: "+502", phoneLength: 8 },
    { flag: "🇬🇳", iso: "gn", name: "Guinea", code: "+224", phoneLength: 8 },
    { flag: "🇬🇼", iso: "gw", name: "Guinea-Bissau", code: "+245", phoneLength: 7 },
    { flag: "🇬🇾", iso: "gy", name: "Guyana", code: "+592", phoneLength: 7 },
    { flag: "🇭🇹", iso: "ht", name: "Haiti", code: "+509", phoneLength: 8 },
    { flag: "🇭🇳", iso: "hn", name: "Honduras", code: "+504", phoneLength: 8 },
    { flag: "🇭🇰", iso: "hk", name: "Hong Kong", code: "+852", phoneLength: 8 },
    { flag: "🇭🇺", iso: "hu", name: "Hungary", code: "+36", phoneLength: 9 },
    { flag: "🇮🇸", iso: "is", name: "Iceland", code: "+354", phoneLength: 7 },
    { flag: "🇮🇳", iso: "in", name: "India", code: "+91", phoneLength: 10 },
    { flag: "🇮🇩", iso: "id", name: "Indonesia", code: "+62", phoneLength: 10 },
    { flag: "🇮🇷", iso: "ir", name: "Iran", code: "+98", phoneLength: 10 },
    { flag: "🇮🇶", iso: "iq", name: "Iraq", code: "+964", phoneLength: 10 },
    { flag: "🇮🇪", iso: "ie", name: "Ireland", code: "+353", phoneLength: 9 },
    { flag: "🇮🇱", iso: "il", name: "Israel", code: "+972", phoneLength: 9 },
    { flag: "🇮🇹", iso: "it", name: "Italy", code: "+39", phoneLength: 10 },
    { flag: "🇯🇲", iso: "jm", name: "Jamaica", code: "+1", phoneLength: 10 },
    { flag: "🇯🇵", iso: "jp", name: "Japan", code: "+81", phoneLength: 10 },
    { flag: "🇯🇴", iso: "jo", name: "Jordan", code: "+962", phoneLength: 9 },
    { flag: "🇰🇿", iso: "kz", name: "Kazakhstan", code: "+7", phoneLength: 10 },
    { flag: "🇰🇪", iso: "ke", name: "Kenya", code: "+254", phoneLength: 9 },
    { flag: "🇰🇮", iso: "ki", name: "Kiribati", code: "+686", phoneLength: 8 },
    { flag: "🇰🇼", iso: "kw", name: "Kuwait", code: "+965", phoneLength: 8 },
    { flag: "🇰🇬", iso: "kg", name: "Kyrgyzstan", code: "+996", phoneLength: 9 },
    { flag: "🇱🇦", iso: "la", name: "Laos", code: "+856", phoneLength: 9 },
    { flag: "🇱🇻", iso: "lv", name: "Latvia", code: "+371", phoneLength: 8 },
    { flag: "🇱🇧", iso: "lb", name: "Lebanon", code: "+961", phoneLength: 8 },
    { flag: "🇱🇸", iso: "ls", name: "Lesotho", code: "+266", phoneLength: 8 },
    { flag: "🇱🇷", iso: "lr", name: "Liberia", code: "+231", phoneLength: 7 },
    { flag: "🇱🇾", iso: "ly", name: "Libya", code: "+218", phoneLength: 8 },
    { flag: "🇱🇮", iso: "li", name: "Liechtenstein", code: "+423", phoneLength: 7 },
    { flag: "🇱🇹", iso: "lt", name: "Lithuania", code: "+370", phoneLength: 8 },
    { flag: "🇱🇺", iso: "lu", name: "Luxembourg", code: "+352", phoneLength: 9 },
    { flag: "🇲🇴", iso: "mo", name: "Macau", code: "+853", phoneLength: 8 },
    { flag: "🇲🇰", iso: "mk", name: "North Macedonia", code: "+389", phoneLength: 8 },
    { flag: "🇲🇬", iso: "mg", name: "Madagascar", code: "+261", phoneLength: 9 },
    { flag: "🇲🇼", iso: "mw", name: "Malawi", code: "+265", phoneLength: 9 },
    { flag: "🇲🇾", iso: "my", name: "Malaysia", code: "+60", phoneLength: 10 },
    { flag: "🇲🇻", iso: "mv", name: "Maldives", code: "+960", phoneLength: 7 },
    { flag: "🇲🇱", iso: "ml", name: "Mali", code: "+223", phoneLength: 8 },
    { flag: "🇲🇹", iso: "mt", name: "Malta", code: "+356", phoneLength: 8 },
    { flag: "🇲🇭", iso: "mh", name: "Marshall Islands", code: "+692", phoneLength: 7 },
    { flag: "🇲🇷", iso: "mr", name: "Mauritania", code: "+222", phoneLength: 8 },
    { flag: "🇲🇺", iso: "mu", name: "Mauritius", code: "+230", phoneLength: 7 },
    { flag: "🇲🇽", iso: "mx", name: "Mexico", code: "+52", phoneLength: 10 },
    { flag: "🇫🇲", iso: "fm", name: "Micronesia", code: "+691", phoneLength: 7 },
    { flag: "🇲🇩", iso: "md", name: "Moldova", code: "+373", phoneLength: 8 },
    { flag: "🇲🇨", iso: "mc", name: "Monaco", code: "+377", phoneLength: 8 },
    { flag: "🇲🇳", iso: "mn", name: "Mongolia", code: "+976", phoneLength: 8 },
    { flag: "🇲🇪", iso: "me", name: "Montenegro", code: "+382", phoneLength: 8 },
    { flag: "🇲🇸", iso: "ms", name: "Montserrat", code: "+1", phoneLength: 10 },
    { flag: "🇲🇦", iso: "ma", name: "Morocco", code: "+212", phoneLength: 9 },
    { flag: "🇲🇿", iso: "mz", name: "Mozambique", code: "+258", phoneLength: 9 },
    { flag: "🇲🇲", iso: "mm", name: "Myanmar", code: "+95", phoneLength: 9 },
    { flag: "🇳🇦", iso: "na", name: "Namibia", code: "+264", phoneLength: 7 },
    { flag: "🇳🇷", iso: "nr", name: "Nauru", code: "+674", phoneLength: 7 },
    { flag: "🇳🇵", iso: "np", name: "Nepal", code: "+977", phoneLength: 10 },
    { flag: "🇳🇱", iso: "nl", name: "Netherlands", code: "+31", phoneLength: 9 },
    { flag: "🇳🇿", iso: "nz", name: "New Zealand", code: "+64", phoneLength: 9 },
    { flag: "🇳🇮", iso: "ni", name: "Nicaragua", code: "+505", phoneLength: 8 },
    { flag: "🇳🇪", iso: "ne", name: "Niger", code: "+227", phoneLength: 8 },
    { flag: "🇳🇬", iso: "ng", name: "Nigeria", code: "+234", phoneLength: 10 },
    { flag: "🇳🇺", iso: "nu", name: "Niue", code: "+683", phoneLength: 4 },
    { flag: "🇰🇵", iso: "kp", name: "North Korea", code: "+850", phoneLength: 10 },
    { flag: "🇳🇴", iso: "no", name: "Norway", code: "+47", phoneLength: 8 },
    { flag: "🇴🇲", iso: "om", name: "Oman", code: "+968", phoneLength: 8 },
    { flag: "🇵🇰", iso: "pk", name: "Pakistan", code: "+92", phoneLength: 10 },
    { flag: "🇵🇼", iso: "pw", name: "Palau", code: "+680", phoneLength: 7 },
    { flag: "🇵🇸", iso: "ps", name: "Palestine", code: "+970", phoneLength: 9 },
    { flag: "🇵🇦", iso: "pa", name: "Panama", code: "+507", phoneLength: 8 },
    { flag: "🇵🇬", iso: "pg", name: "Papua New Guinea", code: "+675", phoneLength: 8 },
    { flag: "🇵🇾", iso: "py", name: "Paraguay", code: "+595", phoneLength: 9 },
    { flag: "🇵🇪", iso: "pe", name: "Peru", code: "+51", phoneLength: 9 },
    { flag: "🇵🇭", iso: "ph", name: "Philippines", code: "+63", phoneLength: 10 },
    { flag: "🇵🇱", iso: "pl", name: "Poland", code: "+48", phoneLength: 9 },
    { flag: "🇵🇹", iso: "pt", name: "Portugal", code: "+351", phoneLength: 9 },
    { flag: "🇵🇷", iso: "pr", name: "Puerto Rico", code: "+1", phoneLength: 10 },
    { flag: "🇶🇦", iso: "qa", name: "Qatar", code: "+974", phoneLength: 8 },
    { flag: "🇷🇴", iso: "ro", name: "Romania", code: "+40", phoneLength: 9 },
    { flag: "🇷🇺", iso: "ru", name: "Russia", code: "+7", phoneLength: 10 },
    { flag: "🇷🇼", iso: "rw", name: "Rwanda", code: "+250", phoneLength: 9 },
    { flag: "🇼🇸", iso: "ws", name: "Samoa", code: "+685", phoneLength: 7 },
    { flag: "🇸🇲", iso: "sm", name: "San Marino", code: "+378", phoneLength: 10 },
    { flag: "🇸🇹", iso: "st", name: "Sao Tome and Principe", code: "+239", phoneLength: 7 },
    { flag: "🇸🇦", iso: "sa", name: "Saudi Arabia", code: "+966", phoneLength: 9 },
    { flag: "🇸🇳", iso: "sn", name: "Senegal", code: "+221", phoneLength: 9 },
    { flag: "🇷🇸", iso: "rs", name: "Serbia", code: "+381", phoneLength: 9 },
    { flag: "🇸🇨", iso: "sc", name: "Seychelles", code: "+248", phoneLength: 7 },
    { flag: "🇸🇱", iso: "sl", name: "Sierra Leone", code: "+232", phoneLength: 8 },
    { flag: "🇸🇬", iso: "sg", name: "Singapore", code: "+65", phoneLength: 8 },
    { flag: "🇸🇽", iso: "sx", name: "Sint Maarten", code: "+1", phoneLength: 10 },
    { flag: "🇸🇰", iso: "sk", name: "Slovakia", code: "+421", phoneLength: 9 },
    { flag: "🇸🇮", iso: "si", name: "Slovenia", code: "+386", phoneLength: 8 },
    { flag: "🇸🇧", iso: "sb", name: "Solomon Islands", code: "+677", phoneLength: 7 },
    { flag: "🇸🇴", iso: "so", name: "Somalia", code: "+252", phoneLength: 8 },
    { flag: "🇿🇦", iso: "za", name: "South Africa", code: "+27", phoneLength: 9 },
    { flag: "🇰🇷", iso: "kr", name: "South Korea", code: "+82", phoneLength: 10 },
    { flag: "🇸🇸", iso: "ss", name: "South Sudan", code: "+211", phoneLength: 9 },
    { flag: "🇪🇸", iso: "es", name: "Spain", code: "+34", phoneLength: 9 },
    { flag: "🇱🇰", iso: "lk", name: "Sri Lanka", code: "+94", phoneLength: 9 },
    { flag: "🇰🇳", iso: "kn", name: "St. Kitts and Nevis", code: "+1", phoneLength: 10 },
    { flag: "🇱🇨", iso: "lc", name: "St. Lucia", code: "+1", phoneLength: 10 },
    { flag: "🇻🇨", iso: "vc", name: "St. Vincent & Grenadines", code: "+1", phoneLength: 10 },
    { flag: "🇸🇩", iso: "sd", name: "Sudan", code: "+249", phoneLength: 9 },
    { flag: "🇸🇷", iso: "sr", name: "Suriname", code: "+597", phoneLength: 7 },
    { flag: "🇸🇪", iso: "se", name: "Sweden", code: "+46", phoneLength: 9 },
    { flag: "🇨🇭", iso: "ch", name: "Switzerland", code: "+41", phoneLength: 9 },
    { flag: "🇸🇾", iso: "sy", name: "Syria", code: "+963", phoneLength: 9 },
    { flag: "🇹🇼", iso: "tw", name: "Taiwan", code: "+886", phoneLength: 9 },
    { flag: "🇹🇯", iso: "tj", name: "Tajikistan", code: "+992", phoneLength: 9 },
    { flag: "🇹🇿", iso: "tz", name: "Tanzania", code: "+255", phoneLength: 9 },
    { flag: "🇹🇭", iso: "th", name: "Thailand", code: "+66", phoneLength: 9 },
    { flag: "🇹🇱", iso: "tl", name: "Timor-Leste", code: "+670", phoneLength: 7 },
    { flag: "🇹🇬", iso: "tg", name: "Togo", code: "+228", phoneLength: 8 },
    { flag: "🇹🇰", iso: "tk", name: "Tokelau", code: "+690", phoneLength: 4 },
    { flag: "🇹🇴", iso: "to", name: "Tonga", code: "+676", phoneLength: 5 },
    { flag: "🇹🇹", iso: "tt", name: "Trinidad and Tobago", code: "+1", phoneLength: 10 },
    { flag: "🇹🇳", iso: "tn", name: "Tunisia", code: "+216", phoneLength: 8 },
    { flag: "🇹🇷", iso: "tr", name: "Turkey", code: "+90", phoneLength: 10 },
    { flag: "🇹🇲", iso: "tm", name: "Turkmenistan", code: "+993", phoneLength: 8 },
    { flag: "🇹🇨", iso: "tc", name: "Turks and Caicos", code: "+1", phoneLength: 10 },
    { flag: "🇹🇻", iso: "tv", name: "Tuvalu", code: "+688", phoneLength: 5 },
    { flag: "🇺🇬", iso: "ug", name: "Uganda", code: "+256", phoneLength: 9 },
    { flag: "🇺🇦", iso: "ua", name: "Ukraine", code: "+380", phoneLength: 9 },
    { flag: "🇦🇪", iso: "ae", name: "United Arab Emirates", code: "+971", phoneLength: 9 },
    { flag: "🇬🇧", iso: "gb", name: "United Kingdom", code: "+44", phoneLength: 10 },
    { flag: "🇺🇸", iso: "us", name: "United States", code: "+1", phoneLength: 10 },
    { flag: "🇺🇾", iso: "uy", name: "Uruguay", code: "+598", phoneLength: 8 },
    { flag: "🇺🇿", iso: "uz", name: "Uzbekistan", code: "+998", phoneLength: 9 },
    { flag: "🇻🇺", iso: "vu", name: "Vanuatu", code: "+678", phoneLength: 7 },
    { flag: "🇻🇪", iso: "ve", name: "Venezuela", code: "+58", phoneLength: 10 },
    { flag: "🇻🇳", iso: "vn", name: "Vietnam", code: "+84", phoneLength: 9 },
    { flag: "🇼🇫", iso: "wf", name: "Wallis and Futuna", code: "+681", phoneLength: 6 },
    { flag: "🇾🇪", iso: "ye", name: "Yemen", code: "+967", phoneLength: 9 },
    { flag: "🇿🇲", iso: "zm", name: "Zambia", code: "+260", phoneLength: 9 },
    { flag: "🇿🇼", iso: "zw", name: "Zimbabwe", code: "+263", phoneLength: 9 }
];
